# Generated by Django 4.1.7 on 2023-03-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ads_header', models.CharField(default='Без темы', max_length=64)),
                ('Ads_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TN', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('MC', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'), ('LW', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний ')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=255)),
                ('Comment_Ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulletinBoard.ads')),
                ('Comment_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdsCategory_Ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulletinBoard.ads')),
                ('Ads_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulletinBoard.category')),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='Ads_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulletinBoard.author'),
        ),
        migrations.AddField(
            model_name='ads',
            name='Ads_Category',
            field=models.ManyToManyField(through='BulletinBoard.AdsCategory', to='BulletinBoard.category'),
        ),
    ]
