# Generated by Django 4.1.7 on 2023-03-23 15:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='Ads_field',
            field=tinymce.models.HTMLField(),
        ),
    ]
